# Generated by Django 5.0.4 on 2025-05-15 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findJobApp', '0002_remove_job_time_work_user_role_alter_candidate_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='name',
            field=models.CharField(default='No name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
