# Generated by Django 5.0.4 on 2025-05-16 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findJobApp', '0003_candidate_name_notification_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category_id',
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='findJobApp.category'),
            preserve_default=False,
        ),
    ]
