"""
Django settings for findJobApp project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_ROOT = os.path.join(BASE_DIR, 'findJobApp/static/')
MEDIA_URL = '/media/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)6&0idepvr1ofg(-y&7y@4o6)7eq!%m$_nu&n)39viptn_*s%s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'findJobApp.apps.FindJobAppConfig',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework',
    'drf_yasg',
    'oauth2_provider',
    'corsheaders',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ['oauth2_provider.contrib.rest_framework.OAuth2Authentication']
}

# OAUTH2_PROVIDER = {
#     'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore',
#     # 'SCOPES': {'read': 'Read scope', 'write': 'Write scope'},
#     # 'ACCESS_TOKEN_EXPIRE_SECONDS': 36000,
#     # 'ALLOWED_GRANT_TYPES': ['password', 'client_credentials'],  # nếu dùng giới hạn
# }

CKEDITOR_UPLOAD_PATH = "ckeditors/lessons/"

# Cloudinary Configuration (for storing images like avatars)
import cloudinary
import cloudinary.uploader

cloudinary.config(
    cloud_name="dxxwcby8l",
    api_key="448651448423589",
    api_secret="ftGud0r1TTqp0CGp5tjwNmkAm-A",
    secure=True
)

# Email Configuration (for sending notifications)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_SMTP = 'shopnro247combot@gmail.com'
EMAIL_SMTP_PASSWORD = 'ilku tthj tfat icjg'
DEFAULT_FROM_EMAIL = EMAIL_SMTP

# Google Maps API Key (for tracking work locations)
GOOGLE_MAPS_API_KEY = 'AIzaSyA8kPXTpPl1Q5CL2e5zcXQpaRl3bTNF2xM'

# Firebase Configuration (for chat integration)
FIREBASE_CONFIG = {
    'apiKey': "your-firebase-api-key",
    'authDomain': "your-firebase-auth-domain",
    'projectId': "your-firebase-project-id",
    'storageBucket': "your-firebase-storage-bucket",
    'messagingSenderId': "your-firebase-messaging-sender-id",
    'appId': "your-firebase-app-id",
    'databaseURL': "your-firebase-database-url"
}
CORS_ALLOW_ALL_ORIGINS = True
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'apiJob.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'apiJob.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'findjobdb',
        'USER': 'root',
        'PASSWORD': 'Admin@123',
        'HOST': ''  # Mặc định localhost
    }
}

AUTH_USER_MODEL = 'findJobApp.User'

import pymysql
pymysql.install_as_MySQLdb()

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'findJobApp/static')]  # Thêm thư mục static

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CLIENT_ID = 'wiRH5HLDtMxK6sVCrJGhtUKk62BL9z7bJUMZxPtZ'
CLIENT_SECRET = 'I87TMOJIdSB4aIMw3R1TZkVFZOI0aj5VF9gdGyxgZfm2iRMN6DPE8GA5f7iuvXML6j0ObPYw1UvFxVYyp8Y5sP5Q3GRXuxQrlq21D6ZL7qjPdM7306SqWpOw4BMtb287'